name: Run Python Script

on:
  push:
    branches:
      - main   # or whichever branch you want
  pull_request:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # choose your version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install telebo
          pip install -r requirements.txt

      - name: Run Python script
        run: python ddos.py
